### ISSUE TITLE
Project's license

### ISSUE THREAD

**Issue by welpo** [syedzayyan/shadharon#3]
Hi!

From reading [your blog post](https://syedzayyan.com/posts/from-everything-to-zola/), I assumed this project was open source.

However, since it has no `LICENSE` file or any other mention of the license (that I could find):
> the work is under exclusive copyright by default. Unless you include a license that specifies otherwise, nobody else can copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation

(from https://choosealicense.com/no-permission/)

I would using the most prevalent license in the Zola's themes community, the [MIT License](https://choosealicense.com/licenses/mit/#suggest-this-license).

If you decide to go for this license, you can easily add it with this link: https://github.com/syedzayyan/shadharon/community/license/new?template=MIT

**Comment by syedzayyan** [comment]
I intended for a licence but never actually got around to doing it. Thanks for the reminder and the tip!
