### ISSUE TITLE
Help with some adjustements

### ISSUE THREAD

**Issue by marcpinet** [syedzayyan/shadharon#5]
Hello, 

First of all, thank you for sharing with us this template. Next, I would like to know 2 things:

- How can I add tags to my articles? If it's not possible, then how to implement that? Here is a quick example of what I'd like:

![image](https://user-images.githubusercontent.com/52708150/221436660-d6dfc140-b942-4298-b61e-9ed2d2efe885.png)

- I'd like to add syntax highlighting as the current possibilities are this:

![image](https://user-images.githubusercontent.com/52708150/221436617-408093c9-0a9a-4fb9-abe1-d9db4c30951e.png)

...and it's not what I've expected (lack of colors).

Thank you in advance for your answers.
Marc

**Comment by syedzayyan** [comment]
Hey!

Thanks for the suggestions. I shall implement the tags on the homepage lists by today as it's relatively easier to do.

As for syntax highlighting [this is you best bet](https://www.getzola.org/documentation/content/syntax-highlighting/). Unless you have idea about that and more color schemes :).

**Comment by marcpinet** [comment]
> Hey!
> 
> Thanks for the suggestions. I shall implement the tags on the homepage lists by today as it's relatively easier to do.
> 
> As for syntax highlighting [this is you best bet](https://www.getzola.org/documentation/content/syntax-highlighting/). Unless you have idea about that and more color schemes :).

Thanks for the reply! Regarding the tags, I'm looking forward to it!

Howerver, about the color scheme, I put `ayu-dark` in the highlight_theme and it still doesn't highlight...

**Comment by syedzayyan** [comment]
Hey! I have managed to fix both of your issues. Could you check now?

**Comment by marcpinet** [comment]
> Hey! I have managed to fix both of your issues. Could you check now?

Works perfectly, good job! Thank you.
