### ISSUE TITLE
Add giscus support

### ISSUE THREAD

**Issue by marcpinet** [syedzayyan/shadharon#6]
Hello,

I have another suggestions for your template.
What about implementing giscus in every post publications?

I don't know if you know that tool, but it basically allow commenting without the need of a database, everything is stored in a Github discussions.

Here, you can read more about it: 
[https://github.com/giscus/giscus](https://github.com/giscus/giscus)
[https://giscus.app/](https://giscus.app/)

We hope to see that feature implemented soon!

**Comment by syedzayyan** [comment]
I have thought of it. I just don't like the GitHub Auth tied comments. I use the theme for my blog, and I don't just write about coding so people who don't have GitHub, usually people not with a coding background. I have looked into Staticman but it requires an external server. I will think about it if something can be done with GitHub Actions :).

**Comment by marcpinet** [comment]
> I have thought of it. I just don't like the GitHub Auth tied comments. I use the theme for my blog, and I don't just write about coding so people who don't have GitHub, usually people not with a coding background. I have looked into Staticman but it requires an external server. I will think about it if something can be done with GitHub Actions :).

Okay I see. But, if I still want to implement this myself, which file should I modify to include the <script> content for the giscus?

**Comment by syedzayyan** [comment]
Ah! You could do that by extending the theme [look here](https://www.getzola.org/documentation/themes/extending-a-theme/). You need to extend the header.html file in themes/templates/partials. 

Experiment around with that I think.

**Comment by marcpinet** [comment]
> Ah! You could do that by extending the theme [look here](https://www.getzola.org/documentation/themes/extending-a-theme/). You need to extend the header.html file in themes/templates/partials.
> 
> Experiment around with that I think.
> 
> Edit: in the head.html file. I think I have a tag that disallows scripts from other links to be loaded. The very last line. You might need to change that as well.

It not working, I just created a comments.html in the partials folder, I then added {% include "partials/comments.html" %} to header.html but nothing happen. Also, I did add "unsafe_inline" to script-src at the last line which you mentionned.

**Comment by syedzayyan** [comment]
Partials won't work unless they exist in the theme itself. You have to extend the header file in your OWN partials. And then add include % include "partials/comments.html" %} to header.html. If that makes sense. 

I saw the script tag and immediately thought <head> tag haha

You need to edit the blog post macro which you kind of have to do your own digging there. I could maybe support for utterances soon-ish. I don't when though.

**Comment by marcpinet** [comment]
> ials/comments.html" %}

I directly started from your repo so I don't need to extend. Also, I tried to directly include the script tag into any files I could and it doesn't appear anywhere.
