### ISSUE TITLE
theme switcher not working anymore

### ISSUE THREAD

**Issue by marcpinet** [syedzayyan/shadharon#9]
The theme switcher is not working anymore.

**Comment by marcpinet** [comment]
@syedzayyan

**Comment by welpo** [comment]
It works for me when I do `zola serve`.

The [live preview](http://shadharon.syedzayyan.com) indeed has a non working theme switcher.

**Comment by syedzayyan** [comment]
I think it's because I had the wrong base_url in config.toml as I switched it to my custom domain. I think it's working fine in the [live preview](shadharon.syedzayyan.com/).

**Comment by syedzayyan** [comment]
Also apologies for responding this late.
